const products = [
    {
        _id: 1,
        name: "Lord Ganesha",
        price: 400,
        image: '/images/image1.jpg',
        numReviews: 10,
        rating: 5,
        description: "Ganesha, also spelled Ganesh, also called Ganapati, elephant-headed Hindu god of beginnings, who is traditionally worshipped before any major enterprise and is the patron of intellectuals, bankers, scribes, and authors.",
        countInStock: 10,
    },
    {
        _id: 2,
        name: "Lord Ganesha",
        price: 300,
        rating: 5,
        image: '/images/image2.jpg',
        numReviews: 25,
        description: "Ganesha, also spelled Ganesh, also called Ganapati, elephant-headed Hindu god of beginnings, who is traditionally worshipped before any major enterprise and is the patron of intellectuals, bankers, scribes, and authors.",
        countInStock: 10,
    },
    {
        _id: 3,
        name: "Lord Ganesha",
        price: 600,
        rating: 5,
        numReviews: 19,
        image: '/images/image3.jpg',
        description: "Ganesha, also spelled Ganesh, also called Ganapati, elephant-headed Hindu god of beginnings, who is traditionally worshipped before any major enterprise and is the patron of intellectuals, bankers, scribes, and authors.",
        countInStock: 10,
    },
    {
        _id: 4,
        name: "Lord Ganesha",
        price: 400,
        image: '/images/image4.jpg',
        rating: 4,
        numReviews: 15,
        description: "Ganesha, also spelled Ganesh, also called Ganapati, elephant-headed Hindu god of beginnings, who is traditionally worshipped before any major enterprise and is the patron of intellectuals, bankers, scribes, and authors.",
        countInStock: 10,
    },
    {
        _id: 5,
        name: "Lord Ganesha",
        price: 750,
        rating: 5,
        image: '/images/image5.jpg',
        numReviews: 5,
        description: "Ganesha, also spelled Ganesh, also called Ganapati, elephant-headed Hindu god of beginnings, who is traditionally worshipped before any major enterprise and is the patron of intellectuals, bankers, scribes, and authors.",
        countInStock: 10,
    },
    {
        _id: 6,
        name: "Lord Ganesha",
        price: 500,
        image: '/images/image6.jpg',
        numReviews: 30,
        rating: 5,
        description: "Ganesha, also spelled Ganesh, also called Ganapati, elephant-headed Hindu god of beginnings, who is traditionally worshipped before any major enterprise and is the patron of intellectuals, bankers, scribes, and authors.",
        countInStock: 10,
    },
    {
        _id: 7,
        name: "Lord Ganesha",
        price: 800,
        rating: 3,
        image: '/images/image1.jpg',
        numReviews: 17,
        description: "Ganesha, also spelled Ganesh, also called Ganapati, elephant-headed Hindu god of beginnings, who is traditionally worshipped before any major enterprise and is the patron of intellectuals, bankers, scribes, and authors.",
        countInStock: 10,
    }
]

export default products;